### ISSUE TITLE
Make Dockerfile work with database

### ISSUE THREAD

**Issue by frblo** [datasektionen/dbuggen2#2]
As of right now the Docker container refuses to work as it cannot connect to the local postgresql server, which is a problem. It would be good if this was fixed.

**Comment by foodelevator** [comment]
Får jag en dbuggen-hatt om jag fixar?

**Comment by frblo** [comment]
@foodelevator du kan få lite dbuggen och en glass

**Comment by foodelevator** [comment]
Menar du lite eller lite?

**Comment by frblo** [comment]
@foodelevator det får du fråga vår CTO om

**Comment by frblo** [comment]
@foodelevator det får du fråga vår CPO @KalleLindblad om

**Comment by KalleLindblad** [comment]
Det ska tolkas som lite. Tror jag är Chief Procrastinator Officer

**Comment by foodelevator** [comment]
Ah men vad nice, jag kommer fråga dig @KalleLindblad om ett litet tag isåfall

**Comment by frblo** [comment]
ping @foodelevator
